### ISSUE TITLE
Redirect...where?

### ISSUE THREAD

**Issue by ximbal** [schnatterer/gollum-galore#4]
Hi, giving a try to the login based on the instructions here:

https://hub.docker.com/r/schnatterer/gollum-galore/

```
jwt {
    path /
    redirect /login?backTo={rewrite_uri}
    allow sub demo
    allow sub bob
}
```

How does the `{rewrite_uri}` should look like?

I've tried to launch the docker container instance with:
`
docker run -p 80:80 -e GOLLUM_PARAMS="--allow-uploads --live-preview --base-path /wiki" -e CADDY_PARAMS="-conf /gollum/config/Caddyfile" -v $(pwd):/gollum schnatterer/gollum-galore
`
Notice the `--base-path /wiki` on the `GOLLUM_PARAMS`

Any suggestions?

Thanks

EN

**Comment by schnatterer** [comment]
Have you tried to run out that way?
I think that rewrite_uri is a variable set at runtime.

Also have a look at this: https://github.com/tarent/loginsrv/tree/master/caddy

**Comment by schnatterer** [comment]
Closing this for now.
